security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password:  $2y$12$4pEA8dkGR7HW9SKYA9eePuObJGdsZ7Ak4v5lVhZkufrcXOspwZ6kK
                        roles: ROLE_ADMIN

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic:
                realm: "login: admin, password: admin"
            logout:
                invalidate_session: true
                path:   /logout
                target: /list


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }